const state = { frames: [], timer: null, index: 0 };
const list = document.getElementById('imageList');
const folderInput = document.getElementById('folderInput');
const preview = document.getElementById('frameImage');
const emptyPreview = document.getElementById('emptyPreview');
const frameCount = document.getElementById('frameCount');
const playButton = document.getElementById('playButton');
const stopButton = document.getElementById('stopButton');
const speed = document.getElementById('speed');
const speedValue = document.getElementById('speedValue');
const count = document.getElementById('selectedCount');
const sortSelect = document.getElementById('sortSelect');
const exportButton = document.getElementById('exportButton');
const clearButton = document.getElementById('clearButton');
const exportDialog = document.getElementById('exportDialog');
const exportForm = document.getElementById('exportForm');
const closeExport = document.getElementById('closeExport');
const cancelExport = document.getElementById('cancelExport');
const keyColor = document.getElementById('keyColor');
const colorSwatch = document.getElementById('colorSwatch');
const tolerance = document.getElementById('tolerance');
const toleranceValue = document.getElementById('toleranceValue');
const exportName = document.getElementById('exportName');
const exportQuality = document.getElementById('exportQuality');
const cropSize = document.getElementById('cropSize');
const sheetInfo = document.getElementById('sheetInfo');
const pickerDialog = document.getElementById('pickerDialog');
const pickerImage = document.getElementById('pickerImage');
const pickColorButton = document.getElementById('pickColorButton');
const closePicker = document.getElementById('closePicker');

const naturalCompare = (a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' });
const enabled = () => state.frames.filter(frame => frame.enabled);
function updateControls() { const hasFrames = state.frames.length > 0; const selected = enabled().length; count.textContent = `${selected} selected`; playButton.disabled = !selected; stopButton.disabled = !state.timer; exportButton.disabled = !selected; clearButton.disabled = !hasFrames; sortSelect.disabled = !hasFrames; }
function renderList() { list.innerHTML = ''; if (!state.frames.length) { list.innerHTML = '<p class="empty-list">No PNG images loaded yet.</p>'; updateControls(); return; } state.frames.forEach((frame, i) => { const row = document.createElement('label'); row.className = 'frame-row'; row.draggable = true; row.dataset.index = i; row.innerHTML = `<span class="frame-number">${i + 1}</span><span class="file-name" title="${frame.name}">${frame.name}</span><input class="toggle" type="checkbox" ${frame.enabled ? 'checked' : ''} aria-label="Enable ${frame.name}" />`; row.querySelector('input').addEventListener('change', e => { frame.enabled = e.target.checked; updateControls(); }); row.addEventListener('dragstart', e => { e.dataTransfer.setData('text/plain', i); row.classList.add('dragging'); }); row.addEventListener('dragend', () => row.classList.remove('dragging')); row.addEventListener('dragover', e => e.preventDefault()); row.addEventListener('drop', e => { e.preventDefault(); const from = Number(e.dataTransfer.getData('text/plain')); const to = Number(row.dataset.index); if (from !== to) { const [moved] = state.frames.splice(from, 1); state.frames.splice(to, 0, moved); state.index = 0; renderList(); } }); list.append(row); }); updateControls(); }
function showFrame(index) { const frames = enabled(); if (!frames.length) return; state.index = index % frames.length; const frame = frames[state.index]; preview.src = frame.url; preview.style.display = 'block'; emptyPreview.style.display = 'none'; frameCount.style.display = 'block'; frameCount.textContent = `${state.index + 1} / ${frames.length}`; }
function play() { const frames = enabled(); if (!frames.length) return; stop(); showFrame(state.index); state.timer = window.setInterval(() => showFrame(state.index + 1), 1000 / Number(speed.value)); playButton.textContent = 'Playing'; updateControls(); }
function stop() { if (state.timer) window.clearInterval(state.timer); state.timer = null; playButton.textContent = 'Play'; updateControls(); }
folderInput.addEventListener('change', e => { stop(); state.frames.forEach(frame => URL.revokeObjectURL(frame.url)); const files = [...e.target.files].filter(file => file.type === 'image/png' || file.name.toLowerCase().endsWith('.png')).sort(naturalCompare); state.frames = files.map(file => ({ file, name: file.name, enabled: true, url: URL.createObjectURL(file) })); state.index = 0; preview.style.display = 'none'; frameCount.style.display = 'none'; emptyPreview.style.display = 'block'; renderList(); e.target.value = ''; });
sortSelect.addEventListener('change', () => { const mode = sortSelect.value; state.frames.sort((a, b) => mode === 'natural' ? naturalCompare(a, b) : mode === 'asc' ? a.name.localeCompare(b.name) : b.name.localeCompare(a.name)); state.index = 0; renderList(); });
playButton.addEventListener('click', play); stopButton.addEventListener('click', stop); speed.addEventListener('input', () => { speedValue.textContent = `${speed.value} FPS`; if (state.timer) play(); });
clearButton.addEventListener('click', () => { stop(); state.frames.forEach(frame => URL.revokeObjectURL(frame.url)); state.frames = []; preview.removeAttribute('src'); preview.style.display = 'none'; frameCount.style.display = 'none'; emptyPreview.style.display = 'block'; renderList(); });
function updateSheetInfo() { const frames = enabled().length; const columns = Math.ceil(Math.sqrt(frames)); const rows = Math.ceil(frames / columns); const scale = Number(exportQuality.value); sheetInfo.textContent = `${frames} frames · ${columns} columns × ${rows} rows · ${scale === 1 ? 'original pixels' : `${scale}× export resolution`} · frames are centre-cropped to squares using their original height.`; }
function loadImage(file) { return new Promise((resolve, reject) => { const image = new Image(); const url = URL.createObjectURL(file); image.onload = () => { URL.revokeObjectURL(url); resolve(image); }; image.onerror = reject; image.src = url; }); }
async function topRightColor(file) { const image = await loadImage(file); const canvas = document.createElement('canvas'); canvas.width = 1; canvas.height = 1; const context = canvas.getContext('2d'); context.drawImage(image, image.naturalWidth - 1, 0, 1, 1, 0, 0, 1, 1); const [red, green, blue, alpha] = context.getImageData(0, 0, 1, 1).data; return alpha ? `#${[red, green, blue].map(value => value.toString(16).padStart(2, '0')).join('')}`.toUpperCase() : null; }
function rgb(hex) { const value = hex.trim(); if (!/^#[0-9a-fA-F]{6}$/.test(value)) return null; return [parseInt(value.slice(1, 3), 16), parseInt(value.slice(3, 5), 16), parseInt(value.slice(5, 7), 16)]; }
function updateColorSwatch() { const color = rgb(keyColor.value); colorSwatch.style.background = color ? keyColor.value.trim() : 'transparent'; }
function removeColor(context, width, height, color, amount) { const pixels = context.getImageData(0, 0, width, height); const data = pixels.data; const visited = new Uint8Array(width * height); const queue = []; const edgeTolerance = amount + 32; const isBackgroundLike = index => Math.hypot(data[index] - color[0], data[index + 1] - color[1], data[index + 2] - color[2]) <= edgeTolerance; const add = (x, y) => { const point = y * width + x; const index = point * 4; if (!visited[point] && data[index + 3] && isBackgroundLike(index)) { visited[point] = 1; queue.push(point); } }; for (let x = 0; x < width; x++) { add(x, 0); add(x, height - 1); } for (let y = 1; y < height - 1; y++) { add(0, y); add(width - 1, y); } for (let cursor = 0; cursor < queue.length; cursor++) { const point = queue[cursor]; const x = point % width; const y = Math.floor(point / width); const index = point * 4; const distance = Math.hypot(data[index] - color[0], data[index + 1] - color[1], data[index + 2] - color[2]); const fadeStart = Math.max(0, amount - 12); data[index + 3] = distance <= fadeStart ? 0 : Math.round(data[index + 3] * Math.min(1, (distance - fadeStart) / Math.max(1, edgeTolerance - fadeStart))); if (x) add(x - 1, y); if (x < width - 1) add(x + 1, y); if (y) add(x, y - 1); if (y < height - 1) add(x, y + 1); } context.putImageData(pixels, 0, 0); }
exportButton.addEventListener('click', async () => { const firstFrame = enabled()[0]; if (firstFrame) { const [defaultColor, image] = await Promise.all([topRightColor(firstFrame.file), loadImage(firstFrame.file)]); if (defaultColor) keyColor.value = defaultColor; cropSize.value = image.naturalHeight; } keyColor.setCustomValidity(''); cropSize.setCustomValidity(''); updateColorSwatch(); updateSheetInfo(); exportDialog.showModal(); });
closeExport.addEventListener('click', () => exportDialog.close());
cancelExport.addEventListener('click', () => exportDialog.close());
keyColor.addEventListener('input', () => keyColor.setCustomValidity(/^#[0-9a-fA-F]{6}$/.test(keyColor.value.trim()) ? '' : 'Enter a HEX color such as #000000.'));
keyColor.addEventListener('input', updateColorSwatch);
pickColorButton.addEventListener('click', () => { const firstFrame = enabled()[0]; if (!firstFrame) return; pickerImage.src = firstFrame.url; pickerDialog.showModal(); });
closePicker.addEventListener('click', () => pickerDialog.close());
pickerImage.addEventListener('click', event => { const bounds = pickerImage.getBoundingClientRect(); const x = Math.min(pickerImage.naturalWidth - 1, Math.max(0, Math.floor((event.clientX - bounds.left) * pickerImage.naturalWidth / bounds.width))); const y = Math.min(pickerImage.naturalHeight - 1, Math.max(0, Math.floor((event.clientY - bounds.top) * pickerImage.naturalHeight / bounds.height))); const canvas = document.createElement('canvas'); canvas.width = 1; canvas.height = 1; const context = canvas.getContext('2d'); context.drawImage(pickerImage, x, y, 1, 1, 0, 0, 1, 1); const [red, green, blue] = context.getImageData(0, 0, 1, 1).data; keyColor.value = `#${[red, green, blue].map(value => value.toString(16).padStart(2, '0')).join('')}`.toUpperCase(); keyColor.setCustomValidity(''); updateColorSwatch(); pickerDialog.close(); });
tolerance.addEventListener('input', () => toleranceValue.textContent = tolerance.value);
function updateSheetInfo() { const frames = enabled().length; const columns = Math.ceil(Math.sqrt(frames)); const rows = Math.ceil(frames / columns); const scale = Number(exportQuality.value); const size = Number(cropSize.value) || 0; sheetInfo.textContent = `${frames} frames | ${columns} columns x ${rows} rows | ${size} x ${size}px centre crop | ${scale === 1 ? 'original pixels' : `${scale}x export resolution`}.`; }
exportQuality.addEventListener('change', updateSheetInfo);
cropSize.addEventListener('input', updateSheetInfo);
exportForm.addEventListener('submit', async event => { event.preventDefault(); event.stopImmediatePropagation(); const color = rgb(keyColor.value); const size = Number(cropSize.value); if (!color) { keyColor.setCustomValidity('Enter a HEX color such as #000000.'); keyColor.reportValidity(); return; } if (!Number.isInteger(size) || size < 1 || size > 8192) { cropSize.setCustomValidity('Enter a whole number from 1 to 8192.'); cropSize.reportValidity(); return; } cropSize.setCustomValidity(''); const frames = enabled(); const columns = Math.ceil(Math.sqrt(frames.length)); const rows = Math.ceil(frames.length / columns); const scale = Number(exportQuality.value); const images = await Promise.all(frames.map(frame => loadImage(frame.file))); const canvas = document.createElement('canvas'); canvas.width = columns * size * scale; canvas.height = rows * size * scale; const context = canvas.getContext('2d'); context.imageSmoothingEnabled = true; images.forEach((image, index) => { const sourceCanvas = document.createElement('canvas'); sourceCanvas.width = image.naturalWidth; sourceCanvas.height = image.naturalHeight; const sourceContext = sourceCanvas.getContext('2d'); sourceContext.drawImage(image, 0, 0); removeColor(sourceContext, image.naturalWidth, image.naturalHeight, color, Number(tolerance.value)); const frameCanvas = document.createElement('canvas'); frameCanvas.width = size; frameCanvas.height = size; const frameContext = frameCanvas.getContext('2d'); const cropX = Math.floor((image.naturalWidth - size) / 2); const cropY = Math.floor((image.naturalHeight - size) / 2); const sourceX = Math.max(0, cropX); const sourceY = Math.max(0, cropY); const targetX = Math.max(0, -cropX); const targetY = Math.max(0, -cropY); const cropWidth = Math.min(size - targetX, image.naturalWidth - sourceX); const cropHeight = Math.min(size - targetY, image.naturalHeight - sourceY); if (cropWidth > 0 && cropHeight > 0) frameContext.drawImage(sourceCanvas, sourceX, sourceY, cropWidth, cropHeight, targetX, targetY, cropWidth, cropHeight); const x = (index % columns) * size * scale; const y = Math.floor(index / columns) * size * scale; context.drawImage(frameCanvas, x, y, size * scale, size * scale); }); canvas.toBlob(blob => { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); const fileName = exportName.value.trim().replace(/[\\/:*?"<>|]/g, '-') || 'coding-mantis-sprite-sheet'; link.download = `${fileName.replace(/\.png$/i, '')}.png`; link.click(); URL.revokeObjectURL(link.href); exportDialog.close(); }, 'image/png'); });
exportForm.addEventListener('submit', async event => { event.preventDefault(); const color = rgb(keyColor.value); if (!color) { keyColor.setCustomValidity('Enter a HEX color such as #000000.'); keyColor.reportValidity(); return; } const frames = enabled(); const columns = Math.ceil(Math.sqrt(frames.length)); const rows = Math.ceil(frames.length / columns); const amount = Number(tolerance.value); const scale = Number(exportQuality.value); const images = await Promise.all(frames.map(frame => loadImage(frame.file))); const cellSize = Math.max(...images.map(image => image.naturalHeight)); const canvas = document.createElement('canvas'); canvas.width = columns * cellSize * scale; canvas.height = rows * cellSize * scale; const context = canvas.getContext('2d'); context.imageSmoothingEnabled = true; images.forEach((image, index) => { const size = image.naturalHeight; const sourceCanvas = document.createElement('canvas'); sourceCanvas.width = image.naturalWidth; sourceCanvas.height = image.naturalHeight; const sourceContext = sourceCanvas.getContext('2d'); sourceContext.drawImage(image, 0, 0); removeColor(sourceContext, image.naturalWidth, image.naturalHeight, color, amount); const sourceX = Math.max(0, Math.floor((image.naturalWidth - size) / 2)); const sourceWidth = Math.min(size, image.naturalWidth); const frameCanvas = document.createElement('canvas'); frameCanvas.width = size; frameCanvas.height = size; const frameContext = frameCanvas.getContext('2d'); frameContext.drawImage(sourceCanvas, sourceX, 0, sourceWidth, size, Math.floor((size - sourceWidth) / 2), 0, sourceWidth, size); const x = ((index % columns) * cellSize + Math.floor((cellSize - size) / 2)) * scale; const y = (Math.floor(index / columns) * cellSize + Math.floor((cellSize - size) / 2)) * scale; context.drawImage(frameCanvas, x, y, size * scale, size * scale); }); canvas.toBlob(blob => { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); const fileName = exportName.value.trim().replace(/[\\/:*?"<>|]/g, '-') || 'coding-mantis-sprite-sheet'; link.download = `${fileName.replace(/\.png$/i, '')}.png`; link.click(); URL.revokeObjectURL(link.href); exportDialog.close(); }, 'image/png'); });
updateControls();
